#!/bin/zsh
# vim: set filetype=zsh:
#

alias check_gpu_power="cat /sys/class/drm/card*/device/power_state"

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/doc/pkgfile/command-not-found.zsh

LS_COLORS="di=1;34:ln=1;36:so=1;35:pi=33:ex=1;32:bd=44;37;0:cd=44;37;0:su=41;30;0:sg=46;30;0:tw=42;30;0:ow=43;30;0"

# aliases
alias -s tex=nvim
alias -s html=w3m
alias -s org=w3m
alias ls=lsd
alias cat=bat
# end of aliases

# bindings
unsetopt BEEP
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[H"   beginning-of-line
bindkey "^[[F"   end-of-line
bindkey "^[[3~"  delete-char
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey '^R' history-incremental-search-backward
# end of bindings

# compinstall config
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'l' vi-forward-char
setopt AUTO_PARAM_SLASH
# setopt LIST_PACKED
setopt MENU_COMPLETE
setopt GLOB_COMPLETE
zstyle ':completion:*' verbose yes
zstyle ':completion:*' file-sort modification
zstyle ':completion:*:*:*:*:corrections' format '%F{blue}!- %d (errors: %e) -!%f'
zstyle ':completion:*:*:*:*:descriptions' format '%F{blue}-- %d --%f'
zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors "$LS_COLORS"
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]} m:{[:lower:][:upper:]}={[:upper:][:lower:]} r:|[._-]=* r:|=*'
zstyle ':completion:*' menu select=10
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
# end of compinstall config

# prompt customization
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%b '
setopt PROMPT_SUBST
PROMPT='%F{green}%*%f %F{blue}%~%f %F{red}${vcs_info_msg_0_}%f$ '
autoload -Uz promptinit
promptinit
# end of prompt customization

# Autocompletion
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd completion)
autoload -Uz compinit
compinit
# End of lines added by compinstall

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install
#
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern root regexp)
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# direnv
eval "$(direnv hook zsh)"
# end of direnv

# navi config
eval "$(navi widget zsh)"
# end of navi config

# ztodo config
autoload -Uz ztodo
chpwd() { ztodo; ztodo list }
# end of ztodo config

# startship
if which starship &>/dev/null ; then
	eval "$(starship init zsh)"
fi
# end of starship
